theme: jekyll-theme-minimal
title: Rook Script
description: "A blog about rook script, an alternative writing system for English"

<ul>
  {% for post in site.posts %}
    <li>
      <a href="{{ post.url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>
